name:                RR
version:             0.1.0.0
github:              "graninas/automatic-whitebox-testing-showcase"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "2019 Alexander Granin"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/RR#readme>

dependencies:
- base >= 4.7 && < 5
- free
- uuid
- aeson
- text
- bytestring
- containers
- vector
- process

library:
  source-dirs: src

executables:
  RR-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RR

tests:
  RR-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RR
    - hspec
