name:                app
version:             0.1.0.0
github:              "graninas/automatic-whitebox-testing-showcase"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "2019 Alexander Granin"

dependencies:
- base >= 4.7 && < 5
- free
- uuid
- aeson
- text
- bytestring
- containers
- vector
- process
- flow

library:
  source-dirs:
    - src

executables:
  app:
    main:                Main.hs
    source-dirs:         src/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts

tests:
  app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flow
    - app
    - hspec
